/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bussystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author v801107
 */
public class AssignBus extends javax.swing.JInternalFrame {

    /**
     * Creates new form AssignBus
     */
    public AssignBus() {
        initComponents();
        employeeCBFillData();
        busCBFillData();
        this.getContentPane().setBackground(new Color(216, 191, 216));
    }
    
    Connection con1;
    PreparedStatement pst;
   
    private void employeeCBFillData()
    {
       try
       {
          Class.forName("com.mysql.jdbc.Driver");
          String databaseURL = "jdbc:mysql://localhost:3306/busm";
          Connection con = DriverManager.getConnection(databaseURL,"root","");
          Statement stat = con.createStatement();
          String selectQuery="select eid from employee_details";
          ResultSet rs=stat.executeQuery(selectQuery);
          while(rs.next())
          {
             eidCB.addItem((rs.getString("eid")));
          }
       }
       catch(Exception e)
       {
          System.out.println(e);
       } 
    }
     public void infoMessage(String message,String tittle)
    {
       JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }  
    private void busCBFillData()
    {
       try
       {
          Class.forName("com.mysql.jdbc.Driver");
          String databaseURL = "jdbc:mysql://localhost:3306/busm";
          Connection con = DriverManager.getConnection(databaseURL,"root","");
          Statement stat = con.createStatement();
          String selectQuery="select bus_no from bus_details";
          ResultSet rs=stat.executeQuery(selectQuery);
          while(rs.next())
          {
             busnoCB.addItem((rs.getString("bus_no")));
       }
       }
       catch(Exception e)
       {
          System .out.println(e);
       } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        eidCB = new javax.swing.JComboBox<>();
        busnoCB = new javax.swing.JComboBox<>();
        employeenameTF = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Assign Bus");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Bus No");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Assign");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Reset");

        eidCB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eidCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                eidCBItemStateChanged(evt);
            }
        });
        eidCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidCBActionPerformed(evt);
            }
        });
        eidCB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                eidCBPropertyChange(evt);
            }
        });

        busnoCB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        employeenameTF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Employee Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(eidCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(busnoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(employeenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1)))
                .addGap(61, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eidCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeenameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busnoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eidCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidCBActionPerformed
        
    }//GEN-LAST:event_eidCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String busno1 = busnoCB.getSelectedItem().toString();
        String employeename = employeenameTF.getText();
        String empid = eidCB.getSelectedItem().toString();
               
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }

String insertQuery = "INSERT INTO assign_bus (Bus_Number, Employee_ID) VALUES (?,?)";

try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm", "root", "");
     PreparedStatement preparedStatement = connection.prepareStatement(insertQuery)) {

    preparedStatement.setString(1, busno1);
    preparedStatement.setString(2, empid);

    int rowsAffected = preparedStatement.executeUpdate();

    if (rowsAffected > 0) {
        infoMessage("Record inserted successfully", "Alert!!");
    } else {
        infoMessage("Unable to insert record", "Alert!!");
    }
} catch (SQLException ex) {
    Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
}
  
          
            
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eidCBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_eidCBPropertyChange
       
    }//GEN-LAST:event_eidCBPropertyChange

    private void eidCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_eidCBItemStateChanged
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
} catch (ClassNotFoundException ex) {
    Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
}

String databaseURL = "jdbc:mysql://localhost:3306/busm";
Connection con = null;
        try {
            con = DriverManager.getConnection(databaseURL, "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Statement stat = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }


String a = eidCB.getSelectedItem().toString();

String selectQuery = "SELECT firstname, lastname FROM employee_details WHERE eid = ?";
PreparedStatement preparedStatement = null;
        try {
            preparedStatement = con.prepareStatement(selectQuery);
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            preparedStatement.setString(1, a);
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }

ResultSet rs = null;
        try {
            rs = preparedStatement.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            if (rs.next()) {
                String b = rs.getString("firstname");
                String c = rs.getString("lastname");
                employeenameTF.setText(b + " " + c);
            } else {
                
            }       } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            
rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            preparedStatement.close();
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AssignBus.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_eidCBItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> busnoCB;
    private javax.swing.JComboBox<String> eidCB;
    private javax.swing.JLabel employeenameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}

