/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bussystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import javax.swing.table.DefaultTableModel;

import java.awt.*;

/**
 *
 * @author v801107
 */


public class BookingForm extends javax.swing.JFrame {
    String luser;
    int busno1;
    
    int a;
    
    int count = 0;
    
     String busNo;
     String departdate1;
     int price1;
     
     

    /**
     * Creates new form BookingForm
     * @param username
     */
    private final AddBooking AddBookingReference;

    // Constructor
    public BookingForm(AddBooking addbooking, String username, int busno1) {
        initComponents();
        this.luser = username;
        this.busno1 = busno1;
        labelUpdate();
        this.AddBookingReference = addbooking;
        populateSeatSpinner();
         
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);     
                   
    }
    
    public void clearFieldValue()
     {
       NICTF.setText("");
       firstname1TF.setText("");
       lastname1TF.setText("");
     }
 
    public void infoMessage(String message,String tittle)
    {
       JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    } 
    Connection con1;
    PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void labelUpdate(){
        try {
            int c;
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm","root","");
                
                pst = con1.prepareStatement("SELECT * FROM bus_details WHERE id = ?");
                pst.setInt(1, busno1); 

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
    
                    busNo = rs.getString("bus_no");
                    String movement1 = rs.getString("bus_no");
                    String bussource = rs.getString("bus_source");
                    String busdest = rs.getString("bus_dest");
                    Date departDate = rs.getDate("depart_date");
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    departdate1 = sdf.format(departDate);
                    String departtime = rs.getString("depart_time");
                    price1 = rs.getInt("price");
                    int seat1 = rs.getInt("total_seat");
                    
                    
                    busno1TF.setText(busNo);
                    movement1TF.setText(movement1);
                    bussource1TF.setText(bussource);
                    busdest1TF.setText(busdest);
                    departdate1TF.setText(departdate1);
                    departtime1TF.setText(departtime);
                    price1TF.setText(Integer.toString(price1));
                    seat1TF.setText(Integer.toString(seat1));
                    
                } else {
    
                    busno1TF.setText("No matching row");
                 }

        
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BookingForm.class.getName()).log(Level.SEVERE, null, ex);
            }
   
            
        } catch (SQLException ex) {
            Logger.getLogger(BookingForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        busno1TF = new javax.swing.JLabel();
        bussource1TF = new javax.swing.JLabel();
        departdate1TF = new javax.swing.JLabel();
        price1TF = new javax.swing.JLabel();
        movement1TF = new javax.swing.JLabel();
        busdest1TF = new javax.swing.JLabel();
        departtime1TF = new javax.swing.JLabel();
        seat1TF = new javax.swing.JLabel();
        firstname1TF = new javax.swing.JTextField();
        NICTF = new javax.swing.JTextField();
        lastname1TF = new javax.swing.JTextField();
        spinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Booking Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Bus No");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Bus Dest");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Bus Source");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Depart Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Available Seat");

        jLabel7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jLabel7AncestorRemoved(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Price/Seat");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Seat No");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Depart Time");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("NIC No.");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Movement");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setText("First Name");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setText("Last Name");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        busno1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        busno1TF.setText("label1");

        bussource1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bussource1TF.setText("label1");

        departdate1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        departdate1TF.setText("label1");

        price1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price1TF.setText("label1");

        movement1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        movement1TF.setText("label1");

        busdest1TF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        busdest1TF.setText("label1");

        departtime1TF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        departtime1TF.setText("label1");

        seat1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        seat1TF.setText("label1");

        firstname1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        NICTF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        lastname1TF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(152, 152, 152))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)))
                                .addGap(13, 13, 13)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(43, 43, 43)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(price1TF)
                                                    .addComponent(departdate1TF)
                                                    .addComponent(bussource1TF)
                                                    .addComponent(busno1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(80, 80, 80)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel6)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(firstname1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(135, 135, 135)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel11))))))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lastname1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(departtime1TF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(busdest1TF)
                                            .addComponent(movement1TF)
                                            .addComponent(seat1TF)
                                            .addComponent(NICTF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 334, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(movement1TF))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(busno1TF)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(bussource1TF)
                            .addComponent(busdest1TF))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(departdate1TF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(departtime1TF))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(seat1TF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(price1TF)
                                    .addComponent(jLabel8))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(NICTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lastname1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstname1TF)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel7AncestorRemoved
        
    }//GEN-LAST:event_jLabel7AncestorRemoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 

    int seatCount = 1;
    Object selectedValue = spinner.getValue();
    int seatNo = Integer.parseInt(selectedValue.toString());
    String nic = NICTF.getText();
    String fName = firstname1TF.getText();
    String lName = lastname1TF.getText();
    String paymentstatus1 = "NO";

    if (nic.isEmpty() || fName.isEmpty() || lName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill out all fields!!", "Alert !!", JOptionPane.ERROR_MESSAGE);
    } else if (!validateNIC(nic)) {
        JOptionPane.showMessageDialog(this, "NIC is not valid. Please enter a valid NIC.");
        NICTF.setText("");
    } else {
        String insertQuery = "INSERT INTO booking_details (booking_user, journey_date, bus_no, seat_no, payment_status, firstname, lastname, nic_no) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm", "root", "");
             PreparedStatement preparedStatement = connection.prepareStatement(insertQuery, Statement.RETURN_GENERATED_KEYS)) {

            preparedStatement.setString(1, luser);
            preparedStatement.setString(2, departdate1);
            preparedStatement.setString(3, busNo);
            preparedStatement.setInt(4, seatNo);
            preparedStatement.setString(5, paymentstatus1);
            preparedStatement.setString(6, fName);
            preparedStatement.setString(7, lName);
            preparedStatement.setString(8, nic);

            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                int bookingID;

                try (ResultSet generatedKeys = preparedStatement.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        bookingID = generatedKeys.getInt(1);
                        AddBookingReference.bookingTableUpdate(bookingID);
                    } else {
                        JOptionPane.showMessageDialog(null, "Couldn't update the Booking table!", "Error", JOptionPane.ERROR_MESSAGE);
      
                    }
                }
            }

                // Update bus details
                String updateQuery = "UPDATE bus_details SET total_seat = (total_seat - ?) WHERE id = ?";
                try (PreparedStatement preparedStatement1 = connection.prepareStatement(updateQuery)) {
                    preparedStatement1.setInt(1, seatCount);
                    preparedStatement1.setInt(2, busno1);

                    int rowsAffectedUpdate = preparedStatement1.executeUpdate();

                    if (rowsAffectedUpdate <= 0) {
                        infoMessage("Something went wrong, Unable to update bus details", "Alert!!");
                    }
                
               int result = JOptionPane.showConfirmDialog(
    null,
    "Your booking was successful!",
    "Success",
    JOptionPane.DEFAULT_OPTION,
    JOptionPane.INFORMATION_MESSAGE
);

if (result == JOptionPane.OK_OPTION || result == JOptionPane.CLOSED_OPTION) {
    // Dispose the BookingForm
    dispose();
}

                
        }
            }catch (SQLException e) {
        }
    }
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private int getRowCountFromQuery(String query, String busNumber) throws SQLException {
    int rowCount = 0;
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm", "root", "")) {
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, busNumber); // Set the bus number parameter
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    rowCount = resultSet.getInt(1); // Or resultSet.getLong(1) for large counts
                }
            }
        }
    }
    return rowCount;
}
    
      private void populateSeatSpinner() {
        try {
             
            String busNumber = busno1TF.getText();
            
            String query = "SELECT count(*) FROM booking_details WHERE bus_no = ?";
            int rowCount = getRowCountFromQuery(query, busNumber);
            
            // Step 1: Retrieve total seat count from bus_details table for the specified bus
            int totalseats1 = getTotalSeatCountFromBusDetails(busNumber);
            
            int totalseats = totalseats1 + rowCount;

            // Step 2: Generate a list of seat numbers from 1 to totalSeats
            List<Integer> allSeatNumbers = new ArrayList<>();
            for (int i = 1; i <= totalseats; i++) {
                allSeatNumbers.add(i);
            }

            // Step 3: Retrieve already booked seat numbers from booking_details table for the specified bus
            List<Integer> bookedSeatNumbers = getBookedSeatNumbersFromBookingDetails(busNumber);

            // Step 4: Remove booked seat numbers from the list
            allSeatNumbers.removeAll(bookedSeatNumbers);

            // Step 5: Populate the spinner with remaining available seat numbers
            SpinnerListModel spinnerModel = new SpinnerListModel(allSeatNumbers);
            spinner.setModel(spinnerModel);

        } catch (SQLException e) {
            e.printStackTrace(); // Add error handling
        }
    }
            
    private int getTotalSeatCountFromBusDetails(String busNumber) throws SQLException {
        int totalSeats = 0;
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm", "root", "")) {
            String query = "SELECT total_seat FROM bus_details WHERE bus_no = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, busNumber); // Set the bus number parameter
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    if (resultSet.next()) {
                        totalSeats = resultSet.getInt("total_seat");
                    }
                }
            }
        }
        return totalSeats;
    }

    private List<Integer> getBookedSeatNumbersFromBookingDetails(String busNumber) throws SQLException {
        List<Integer> bookedSeatNumbers = new ArrayList<>();
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm", "root", "")) {
            String query = "SELECT seat_no FROM booking_details WHERE bus_no = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, busNumber); // Set the bus number parameter
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    while (resultSet.next()) {
                        bookedSeatNumbers.add(resultSet.getInt("seat_no"));
                    }
                }
            }
        }
        return bookedSeatNumbers;
    }
    
    private boolean validateNIC(String nic) {
    // Define the NIC format using a regular expression
    String nicFormat = "^(\\d{9}V|\\d{12})$";

    // Check if the entered NIC matches the specified format
    return nic.matches(nicFormat);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NICTF;
    private javax.swing.JLabel busdest1TF;
    private javax.swing.JLabel busno1TF;
    private javax.swing.JLabel bussource1TF;
    private javax.swing.JLabel departdate1TF;
    private javax.swing.JLabel departtime1TF;
    private javax.swing.JTextField firstname1TF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname1TF;
    private javax.swing.JLabel movement1TF;
    private javax.swing.JLabel price1TF;
    private javax.swing.JLabel seat1TF;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
