/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bussystem;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author v801107
 */
public class ReservedSeatingPayments extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReservedSeatingPayments
     */
    public ReservedSeatingPayments() {
        initComponents();
        table_update();
        this.getContentPane().setBackground(new Color(255, 255, 204)); 

    }
    Connection con1;
    PreparedStatement pst;
    
     private void table_update()
    {
        try {
            int c;
            
            try {
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm","root","");
                
                pst = con1.prepareStatement("select * from booking_details");
                ResultSet rs = pst.executeQuery();
                
                ResultSetMetaData rsd = rs.getMetaData();
                c= rsd.getColumnCount();
                
                DefaultTableModel d = (DefaultTableModel)jTable1.getModel();            
                d.setRowCount(0);
                
                while(rs.next())
                {
                    Vector v2 = new Vector();
                    
                    for(int i=1; i<=c; i++)
                    {
                        v2.add(rs.getInt("booking_id"));
                        v2.add(rs.getString("booking_user"));
                        v2.add(rs.getDate("journey_date"));
                        v2.add(rs.getString("bus_no"));
                        v2.add(rs.getInt("seat_no"));
                        v2.add(rs.getString("payment_status"));
                        v2.add(rs.getString("firstname"));
                        v2.add(rs.getString("lastname"));
                        v2.add(rs.getString("nic_no"));
                    }
                    
                    d.addRow(v2);
                }
                




                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(EditBusDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(EditBusDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        
    }
     public void infoMessage(String message,String tittle)
    {
       JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }  
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Booking User", "Journey Date", "Bus Number", "Seat Number", "Payment Status", "First Name", "Last Name", "NIC Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("To select multiple records, hold Ctrl while clicking on the desired rows!");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(826, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int selectIndex = jTable1.getSelectedRow();
        if(selectIndex >= 0){
   DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
   String busNo;
   int bookingId = 0;


    int totalPrice = 0;

   
    int[] selectedRows = jTable1.getSelectedRows();
    String paymentstatus1 = null;

    for (int row : selectedRows) {
        if (d1.getValueAt(row, 5).toString().equals("YES")) {
            paymentstatus1 = d1.getValueAt(row, 5).toString();
        }
    }

    if ("YES".equals(paymentstatus1)) {
        infoMessage("Kindly choose only the set of outstanding bookings that require payment!", "Alert !!");
    } else {
        
      
        for (int row : selectedRows) {
            
             
            String id1 = d1.getValueAt(row, 3).toString(); 

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/busm", "root", "");

                pst = con1.prepareStatement("select * from bus_details where bus_no = ?");
                pst.setString(1, id1);

                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    totalPrice += rs.getInt("price");
                }
            } catch (ClassNotFoundException | SQLException ex) {
               
                ex.printStackTrace();
            }
        }

        
        int option = JOptionPane.showConfirmDialog(null, "Total price was: " + totalPrice + ", Do you want to proceed?", "Alert !!", JOptionPane.YES_NO_OPTION);

       
        if (option == JOptionPane.YES_OPTION) {
            
             for (int row : selectedRows) {
                 bookingId = Integer.parseInt(d1.getValueAt(row, 0).toString());
            String updateSql = "UPDATE booking_details SET payment_status = 'YES' WHERE booking_id = ?";
            try (PreparedStatement updatePst = con1.prepareStatement(updateSql)) {
    updatePst.setInt(1, bookingId);

    int rowsUpdated = updatePst.executeUpdate();
    if (rowsUpdated > 0) {
        
        table_update();
                    
                } else {
                    infoMessage("Unable to complete the payment request, please try again", "Alert !!");
                }
            } catch (SQLException ex) {
                    

            }
        }
             infoMessage("Payment Successfull!", "Alert !!");
             
    }

    }
        }
        else
        {
         infoMessage("Please select atleast an outstanding booking to procced with the payment!", "Alert !!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
